components/03 - global/logo/logo.twig

resolves #133
There is still a duplicative id with `uiowa-wordmark` that gets flagged, but unless we create separate svgs for each implementation (header/footer) this still dings us. separate svg components slow performance.

Logo - Remove id, add aria-labelledby and role

---

src/components/hero/_hero.scss
src/components/hero/hero.js
src/components/menus/top/_top.scss
src/components/search-toggle/_search-toggle.scss

In this PR:
- Updates to mobile search button, top links, and search form to reduce new spacing overlap regression. 
- `hero.js` update to add `aria-label` for each button state. 
- `_hero.scss` cleanup missed from earlier release.

Feature: mobile search updates / aria-label for hero play/pause button

---

src/components/search-toggle/_search-toggle.scss
src/components/search-toggle/search-toggle--bttn.twig
src/components/search-toggle/search-toggle--overlay.twig
src/components/search-toggle/search-toggle.js
src/components/search-toggle/search-toggle.twig

This PR attempts to resolve the a11y issue reported by @inspector508 along with some other tweaks:
>Search button doesn’t announce changes in aria-expanded value.
https://github.com/uiowa/uiowa/issues/1437#issuecomment-634686264
The initial problem appears to be that the current implementation forces a focus change to the search input before the aria-expanded value on the toggle button is announced. The force focus change was done to lead the user back up the DOM where the search input is instead of out to the next element (main menu).
I changed the DOM order after talking with @bspeare and removed the forced focus change. I also added similar aria-controls information to the markup similar to the accordion component. I also believe there was misuse of `aria-expanded` on the …

tweak a11y related to search-toggle

---

theme/views/layouts/skeleton.nunj

* Run locally: `npm run watch`
* Inspect the page and verify that GTM tracking code is placed in the `<head>` of the document. Confirm also that the `<noscript>` fallback is placed at the beginning of the `<body>`.

Feature: Added GTM tracking code.

---

src/components/hero/_hero.scss

- Removed hero-center style targeting centered text margins
Verify that hero center paragraph text does not look off centered.

Feature: Quick fixes for a 3.0.1 release

---

src/components/event/event.config.yml
src/components/event/event.scss
src/components/event/event.twig

resolves #276
Go to https://uids.brand.uiowa.edu/branches/feature_event_fallback_updates/components/detail/events-block.html and verify that an event without an image appears full-width of it's row container.

Feature: Events component fix

---

src/components/accordion/accordion.scss

Resolves https://github.com/uiowa/uids/issues/282. 
- Removed `font-size: inherit` for accordion `<p>` so that font sizes within the accordion will follow the same size as content within a basic text area. 
https://uids.brand.uiowa.edu/branches/feature_accordion_text/components/detail/accordion--multi.html

Feature: Accordion content text size and padding adjustments

---

src/components/alert/alert.scss

It looks like the hawk alert body does not contain a `<p>` so I have adjusted so that it will work for both `<p>` and `<span>` to resolve https://github.com/uiowa/uiowa/issues/2097.

Feature: Hawk Alert quick fix

---

src/components/banner/banner.scss

Fixes pull request #2466. https://github.com/uiowa/uiowa/pull/2466
Adds white, gray, light banner background color options.

Added functionality for white, gray, light banner background

---

src/components/slider/slider--multiple.twig
src/components/slider/slider.scss

* `npm run watch`
* View https://localhost:3000/components/preview/slider--multiple and observe that the second slider is shown.

Hotfix: Display slider correctly when it is inside of a 'display: flex' container

---

src/components/button/button.scss

https://github.com/uiowa/uiowa/issues/2566
1. Add all button variants to kitchen sink page (https://localhost:3000/components/detail/kitchen-sink): 
```
<a href="https://www.example.com" class="bttn bttn--tertiary bttn--caps">
More News
<i class="fas fa-arrow-right"></i>
</a>
<a href="https://www.example.com" class="bttn bttn--primary bttn--caps">
More News
<i class="fas fa-arrow-right"></i>
</a>
<a href="https://www.example.com" class="bttn bttn--secondary bttn--caps">
More News
<i class="fas fa-arrow-right"></i>
</a>
<a href="https://www.example.com" class="bttn bttn--outline bttn--tertiary bttn--caps">
More News
<i class="fas fa-arrow-right"></i>
</a>
<a href="https://www.example.com" class="bttn bttn--outline bttn--tertiary bttn--sans-serif">
More News
<i class="fas …
```

Updated button link styling to accomodate for gold based backgrounds

---

src/components/card/_card-mixins.scss
src/components/card/card.scss

Resolves https://github.com/uiowa/uids/issues/427.
- Add `bg--gold` to card wrapper on https://localhost:3000/components/detail/card--centered. 
- Add ` card__media--medium` to media container.

Feature: card padding fixes

---

src/components/typography/paragraph/paragraph.scss

We currently allow the `<mark>` tag in our WYSIWYG. Reset.css makes it highlighter yellow. May I suggest an on-brand mark?
before:
after:

add primary color for mark tag

---

src/components/video/video.js

* Adds a check that the video container element and the video element exist before running the rest of the javascript.
* Converts Video object methods to be static since they don't need to reference `this`.
* Check that https://uids.brand.uiowa.edu/branches/hotfix_video_check/components/detail/banner--video still works.
* Check that https://uids.brand.uiowa.edu/branches/hotfix_video_check/components/detail/banner--multiple still works.

Hotfix: Video updates

---

src/components/stat/stat.scss

This pr fixes a stat regression that loses it centering if the stat contains `stat__content`. 
Compare https://uids.brand.uiowa.edu/components/preview/stat--row.html against https://uids.brand.uiowa.edu/branches/feature_stat_regression_updates/components/preview/stat--row.html and notice how the hover in this feature branch does not pop all the way to the top of the grid container.

Feature: Fix for stat hover regression

---

src/components/colors/colors.scss

This pr adds a few text utility color classes. 
- Go to the Kitchen sink page and try adding `text--gray` to one of the headlines on a white background that isn't linked up.  The heading should change color.

Feature: Added text utility colors

---

src/components/menus/main-menu/main-menu.scss

This Pr Fixes a style problem with Horizontal menus at lower breakpoints.
1. Pull down this branch 
2. Change the `hidden: true` value on the second line of `src/components/menus/main-menu/main-menu.config.yml` to `hidden: false` (Do not commit this)
3. Spin up your local site with `npm run watch`
2. Under Menus > Main Menu check that all horizontal styles at less than 768px have no down arrow, and that the tab/arrow styles only appear at greater breakpoints.
What you do not want to see:
What you do want to see:

horizontal nav fix

---

src/components/tables/tables.scss

hotfix to fix sizing issue. Borders were being added where they were not needed, and making the width calculations mess up.

fixing table striped border issue

---

.github/workflows/gh-pages.yml
README.md
package.json
src/components/tables/table-responsive--UNUSED/table-responsive.js
src/components/tables/table-responsive--UNUSED/table-responsive.scss
src/components/tables/tables--responsive.twig
src/components/tables/tables.config.yml
src/components/tables/tables.js
src/components/tables/tables.scss
src/components/tables/tables.twig

Resolves #509
Resolves #510 
https://uids.brand.uiowa.edu/branches/feature_default_tables/components/detail/tables.html
Check different table examples. The previous responsive behavior has been removed in favor of a horizontal scroll that is in effect below the `sm` breakpoint. Sticky headers (top or left) will no longer work. Compare the tables with the current tables to see if anything appears broken in appearance.
There is a hidden example of using a wrapping div for adding horizontal scrolling to larger tables beyond the `sm` breakpoint. To view it, set the responsive variant to not be hidden locally in `src/components/tables/tables.config.yml` and view the resulting page that is added to the documentation.

Feature: Default table styles

---

src/components/typography/paragraph/paragraph.scss

Resolves https://github.com/uiowa/uids/issues/550. 
- Go to https://localhost:3000/components/detail/paragraph and verify that the underline is present on link hover and the blue color changes to black.

Feature:`<a>` hover adjustments for a11y

---

src/components/typography/paragraph/paragraph.scss

Proposed changes to Intro Text feature.
- Smaller font size. Feels odd to have the intro text larger than the H2.
- Increased line-height for spacing
- Removes additional margin-bottom and defaults to regular paragraph margin-bottom.
Before
After

Intro Text Changes

---

src/components/typography/lists/lists.scss

Resolves https://github.com/uiowa/uids/issues/576. 
- Go to https://uids.brand.uiowa.edu/branches/feature_ul_no_lists/components/detail/lists.html and add the class `element--list-none` to a `<ul>` or `<ol>` and verify that the bullet or number does not display.

Feature: Added `<ul>` modifier to remove bullet or number if used on ul or ol

---

src/components/card/card.config.yml
src/components/card/card.scss

This resolves an issue with using left/right media alignment with content centering on the cards. 
Go to the pages below and verify that they don't look like the garbled screenshot above:
- https://uids.brand.uiowa.edu/branches/feature-card-fix/components/detail/card--horizontal-large-centered-left.html
- https://uids.brand.uiowa.edu/branches/feature-card-fix/components/detail/card--horizontal-large-centered-right.html

Feature: Added fix for card right/left with center alignment

---

src/components/card/card.scss

resolves https://github.com/uiowa/uiowa/issues/4748.
Adds width to small stacked images so the empty profile image doesn't disappear.

Update to card images

---

src/components/background/background.scss
src/components/colors/colors.scss
src/components/kitchen-sink/kitchen-sink.twig
src/components/menus/main-menu/main-menu.scss
src/components/tables/tables.scss
src/components/typography/paragraph/paragraph.scss

Resolves https://github.com/uiowa/uiowa/issues/4455
- Go to the kitchen sink and verify that the `<figcaption>` is readable on all background colors and links within are blue on white and gray backgrounds. https://uids.brand.uiowa.edu/branches/feature_figcaption_fix/components/preview/kitchen-sink.html. Try adding `bg--` colors to the body class and verify that the captions are still accessible. 
- Try adding `bg--white` and `bg--gray` background colors to https://uids.brand.uiowa.edu/branches/feature_figcaption_fix/components/preview/main-menu.html and verify that the link color does not turn blue. 
- Go to https://uids.brand.uiowa.edu/branches/feature_figcaption_fix/components/preview/kitchen-sink.html and verify that link color within table caption is gold on all background colors. …

Feature: A few misc follow-ups to links on gray background colors

---

src/components/accordion/accordion--focus-test.twig
src/components/accordion/accordion--multiple.twig
src/components/accordion/accordion.config.yml
src/components/accordion/accordion.js
src/components/accordion/accordion.twig

This should start to be able to allow accordions to have hash parameter functionality.
- On https://localhost:3000/components/preview/accordion--default , test that clicking on different accordion items changes the hash parameter in the URL, and that closing an item clears the URL hash parameter.
- On the same page, check that changing the URL to another viable hash parameter also opens that accordion.
- Open a new tab and past in a URL of the page you just visited with a hash parameter and verify that the correct accordion item opens.
- On the same page, disable JS and CSS and verify that you can see all the accordion data, even if it is ugly.
- On https://localhost:3000/components/preview/accordion--multi , verify that clicking on different accordion items changes the hash parameter in …

refactor accordions to accept hash parameters
