assets/scss/_utilities.scss
components/01 - elements/button/_button.scss
components/01 - elements/button/button.config.yml
components/01 - elements/button/button.twig
components/03 - global/menus/top/_top.scss

This feature refactors the button component for #31

Feature: Refactor button component

---

components/02 - blocks/portraits-block/portraits-block--basic.twig
components/02 - blocks/portraits-block/portraits-block.js

Followed the blueprint listed on #177 as it pertains to UIDS.

remove label id from portraits

---

gulpfile.js
src/assets/scss/_base.scss
src/components/banner/_banner.scss
src/components/hero/_hero.scss
src/components/menus/main-menu/_main-menu.scss
src/components/menus/top/_top.scss
src/components/wip/hero-block/_hero-block.scss
src/components/wip/hero-block/hero-block.config.yml
src/components/wip/hero-block/hero-block.js
src/components/wip/hero-block/hero-block.twig

- Style adjustments for https://github.com/uiowa/uiowa/pull/1622. 
- Play/pause position size and placement adjustments for https://github.com/uiowa/uiowa/issues/1680. 
- Added `.mobile-display` class for displaying elements for mobile view only.

Feature: Sidebar style updates / video button updates

---

src/components/search-toggle/search-toggle--bttn.twig

Fixes https://github.com/uiowa/uiowa/issues/1669

Add aria-labelledby to search button

---

src/components/branding/footer/footer.twig
src/components/branding/iowa-bar/iowa-bar.twig
src/components/branding/logo/logo.twig

Wordmark accessibility fix

---

src/components/event/event.config.yml
src/components/event/event.scss

Resolves https://github.com/uiowa/uids/issues/284
https://uids.brand.uiowa.edu/branches/feature_event_alignment_fix/components/detail/events-block.html

Feature: Event component centering adjustment

---

src/components/banner/banner.scss

Feature: Remove vertical alignment for banner bottom positioning

---

.github/workflows/gh-pages.yml

Changed `set-env` variable to `set-output` and updated the `actions/setup-node` version.
Hoping this fixes the deprecated code that's causing the builds to fail
Closes #413

Added start to potential env variable fix

---

src/components/typography/paragraph/paragraph.scss
src/components/typography/paragraph/paragraph.twig

Resolves https://github.com/uiowa/uids/issues/415. 
Go to https://localhost:3000/components/detail/paragraph and verify that the small tag has a different `line-height` than the paragraph text.    Verify that the area of text with the class `small--inline` will display inline with the paragraph text with the same `line-height` as the paragraph.

Feature: small tag adjustments

---

src/components/banner/banner.scss
src/components/banner/banner.twig

Resolves: https://github.com/uiowa/uids/issues/450
- Verify that default banner heights have been added to `banner.scss`
- Verify that banner gradient styles have been added to `banner.scss`
- Verify that headline size for `banner--large` variant has been added to `banner.scss`
- Verify that custom css has been removed from `banner.twig`
Url: https://uids.brand.uiowa.edu/branches/feature_banner_component_from_uids_base/components/detail/banner--default.html

Feature: update banner component with default height and gradient css from uids_base

---

src/components/layouts/viewbook/viewbook.scss
src/components/menus/vertical-dots/vertical-dots.scss

this adds styles for the new vue template project.
The core structure of these things should be changed eventually to mirror the new classes, but for now this will work.

Template styles

---

src/components/background/background.scss
src/components/blockquote/blockquote.scss
src/components/kitchen-sink/kitchen-sink.config.yml

Resolves https://github.com/uiowa/uids/issues/456. 
Go to https://uids.brand.uiowa.edu/branches/feature_border_colors/components/preview/kitchen-sink.html and compare against border colors on https://uids.brand.uiowa.edu/components/preview/kitchen-sink.html.   The border colors for this branch (https://uids.brand.uiowa.edu/branches/feature_border_colors/components/preview/kitchen-sink.html) should appear more subtle and the blockquote borders show be consistently either gold or white depending on the background color.

Feature: border color updates

---

src/components/tables/tables.scss
src/components/tables/tables.twig

border hotfix

---

src/assets/scss/_utilities.scss
src/components/typography/headings/headings.scss
src/components/typography/paragraph/paragraph.scss

This Pr tracks progress for https://github.com/uiowa/uids/issues/445
Spin up uids locally
Open the paragraphs typography componenet and check that the bold and light intros grow and shrink between 600 and 1310 px
Open the headlines typography componenet and check that all the H tags grow and shrink between 600 and 1310 px

starting on the clampage!

---

src/assets/scss/_utilities.scss
src/components/menus/main-menu/main-menu--children.twig
src/components/menus/main-menu/main-menu.config.yml
src/components/menus/main-menu/main-menu.scss

I480 navigation styles

---

.github/workflows/gh-pages.yml

Removing the delete trigger, for now.

---

src/components/card/card--row.twig
src/components/card/card.config.yml
src/components/card/card.js
src/components/card/card.twig

Resolves https://github.com/uiowa/uids/issues/531. 
- Go to https://uids.brand.uiowa.edu/branches/feature_card_no_link/components/preview/card--row.html and verify that first card has data attribute and that only the card title is clickable.

Feature: Added data attribute for removing entire card link function in card.js

---

src/components/branding/footer/footer.twig

just adding land acknowledgement

Add land acknowledgement link

---

src/components/typography/headings/headings.scss

Missed the font weight adjustment for `.h1`

Feature: quick font weight fix

---

src/components/branding/footer/footer.scss

Adds column-gap to footer__container--flex to fix issue : Resolves #575

Adds column-gap to footer__container--flex

---

src/assets/scss/_base.scss
src/assets/scss/reset.scss

Resolves https://github.com/uiowa/uiowa/issues/3688 and resolves https://github.com/uiowa/uids/issues/462.

Adds scroll-behavior: smooth;

---

src/components/headline/_headline-mixins.scss
src/components/headline/headline.scss

Resolves https://github.com/uiowa/uids/issues/606. 
- Review code changes
- Compare new underline styles https://uids.brand.uiowa.edu/branches/feature_headline_underline_refactor/components/detail/headlines.html against https://uids.brand.uiowa.edu/latest/components/detail/headlines.html.

Feature: `headline--underline` refactor

---

src/components/blockquote/blockquote.config.yml
src/components/blockquote/blockquote.scss
src/components/blockquote/blockquote.twig
src/components/card/card.scss

This pull request updates the blockquote to include variants using a profile image. 
- Review the code in "files changed" based on the criteria outlined below in the "how to review" section
- Test out https://uids.brand.uiowa.edu/branches/feature_blockquote_prototyping/components/detail/blockquote--default.html and compare against https://uids.brand.uiowa.edu/components/detail/blockquote--default.html
- Make suggested fixes in your review or pull the code down locally and adjust the code and push up your suggested fixes.
<details>
- https://uids.brand.uiowa.edu/branches/feature_blockquote_prototyping/components/detail/blockquote--left-with-image-aligned-to-the-left-of-the-content.html
- https://uids.brand.uiowa.edu/branches/feature_blockquote_prototyping/components/detail/blockquote--left- …

Feature: Blockquote image variants

---

src/components/slider/slider.scss

this should fix https://github.com/uiowa/uids/issues/424

add transition offset to block rubberbanding lag

---

src/assets/scss/_breakpoints.scss
src/assets/scss/_grid.scss
src/assets/scss/theme.scss
src/components/alert/alert.scss
src/components/banner/banner.scss
src/components/branding/footer/footer.scss
src/components/branding/iowa-bar/iowa-bar.scss
src/components/branding/logo/logo.scss
src/components/branding/parent-site-name/parent-site-name.scss
src/components/branding/site-name/site-name.scss
src/components/cta/cta.scss
src/components/event/event.scss
src/components/form/search/search.scss
src/components/grid/grid.scss
src/components/hero/_hero.scss
src/components/highlight/highlight.scss
src/components/layouts/viewbook/viewbook.scss
src/components/menus/off-canvas/off-canvas.scss
src/components/menus/quick/_quick.scss
src/components/menus/top/top.scss
src/components/menus/vertical-dots/vertical-dots.scss
src/components/search-toggle/_search-toggle.scss
src/components/slider/slider.scss
src/components/stat/stat.scss
src/components/viewbook/aerial/aerial.scss

Resolves https://github.com/uiowa/uids/issues/622.

Feature: Adjusted menu to md breakpoint for all uses

---

src/components/alert/alert.scss
src/components/background/background.scss
src/components/blockquote/blockquote.scss
src/components/branding/footer/footer.scss
src/components/button/button.scss
src/components/card/card.scss
src/components/cta/cta.config.yml
src/components/cta/cta.scss
src/components/cta/cta.twig
src/components/headline/_headline-mixins.scss
src/components/kitchen-sink/kitchen-sink.config.yml
src/components/kitchen-sink/kitchen-sink.twig
src/components/stat/stat.scss
src/components/tables/tables.scss

Resolves https://github.com/uiowa/uids/issues/651
Resolves https://github.com/uiowa/uids/issues/280
Resolves https://github.com/uiowa/uids/issues/592
Resolves https://github.com/uiowa/uids/issues/411
Go to https://uids.brand.uiowa.edu/branches/feature_bg_gray_link/components/preview/kitchen-sink.html and verify that:
- The link color is blue on gray background if link is within `p, ol, ul, dl, cite` and not using the `bttn` class - **can you think of any other tags we might want to target?**
- Look at the link color within the cards in all sections and the text outside of the card grid.  See screenshots below for examples.   
<details>
</details>
- Blockquote borders remain gold on all background colors except gold if you look at each card on …

Feature: bg gray link fix and a few other background color fixes

---

src/components/background/background.scss
src/components/button/button.scss

After testing on https://sandbox.uiowa.ddev.site/text-area-link-color, this has a few follow-up fixes to get links within tables working.

Feature: A few follow-up link color adjustments

---

src/components/tabs/tabs.js
src/components/tabs/tabs.scss
src/components/tabs/tabs.twig

Check the title for more details.

changing class, better checking for proper structure. Check the description for more details.

---

src/components/accordion/accordion.config.yml
src/components/accordion/accordion.scss
src/components/accordion/accordion.twig

Resolves https://github.com/uiowa/uids/issues/665
- Removes hard-coded text color value
- Sets `bg--white` as default background for accordion content. 
- Add `bg--black`, `bg--gold`, `bg--gray`, `bg--white` to body on https://uids.brand.uiowa.edu/branches/feature_accordion_a11y/components/preview/accordion--default.html for testing.

Feature: Updates to accordion for background colors
